### ISSUE TITLE
How to external reverse proxy

### ISSUE THREAD

**Issue by MrRinkana** [docjyJ/aio-stalwart#48]
Hello!

I'm a bit of a newbie to docker and stalwart both, and I'm a bit confused about how to run with an own reverse proxy.

I'm running caddy but **not** in docker (rather straight on host) that currently terminates ssl for nextcloud aio.

I was reading your readme, but I'm not sure how exactly to mount the certificates into docker:

Where do I mount the volume "nextcloud_aio_caddy"? Into the aio container? How does stalwart-aio get hold of the certificates, do I need to mount the volume into the stalwart container? Does stalwart-aio automatically handle certificate refreshes or do I need to make some hooks in caddy or some cron job to reload stalwart? 

Could you provide an example docker compose for this case (non-docker ssl terminating caddy, aio)?
I have my certificates in: /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/.. on the host.

Is the "another domain" section in the "use your own certificate" part of the readme relevant if one is **not** running the community container? 

Thank you for this community container btw, and sorry if I'm asking something that one should know!

**Comment by docjyJ** [comment]
Hi, are you using the master container?

**Comment by MrRinkana** [comment]
Yep, the aio mastercontainer, its only caddy that is run outside. 

<details><summary>My current docker compose looks like this:</summary>

```yml
# ignored options for 'all-in-one'
# --sig-proxy=false
services:
    all-in-one:
        init: true
        container_name: nextcloud-aio-mastercontainer
        restart: always
        ports:
            - 8080:8080
        network_mode: bridge
        volumes:
            - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - NEXTCLOUD_DATADIR=/srv/ncdata
            - APACHE_PORT=11000
            - APACHE_IP_BINDING=127.0.0.1
            - AIO_COMMUNITY_CONTAINERS="stalwart"
        image: nextcloud/all-in-one:latest

volumes:
    nextcloud_aio_mastercontainer:
        external: true
        name: nextcloud_aio_mastercontainer
```

</details>
